title: [AJINKYA SHYAM POTKAR]
description: [PIPING STRESS ENGINEER]
image: # <img src="./AjinkyaPhoto.jpeg" alt="Ajinkya Potkar" width="50" style="border-radius: 50%;"> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
